substitutions:
  device_name: busstid

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.0.34
    gateway: 10.0.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D1
  scl: D2
  scan: False
  
sensor:
  - platform: homeassistant
    id: first_bus
    entity_id:  sensor.bus_stig_31_first
    internal: true
  - platform: homeassistant
    id: second_bus
    entity_id:  sensor.bus_stig_31_second
    internal: true

font:
  - file: 'slkscr.ttf'
    id: font1
    size: 8
    
  - file: 'BebasNeue-Regular.ttf'
    id: font3
    size: 20

  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 80
  
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    brightness: 40%
    rotation: 90
    lambda: |-
      it.printf(32, 0, id(font1), TextAlign::TOP_CENTER, "Buss Stig");
      it.printf(32, 64, id(font2), TextAlign::CENTER, "%.0f", id(first_bus).state);
      it.printf(64, 128, id(font3), TextAlign::BASELINE_RIGHT, "%.0f", id(second_bus).state);
